const swiperData = [  
    {  
        id: 1,  
        title: "شیلا",  
        image: "/assets/immmg/s1.png",  
        address: "تهران",  
        discount: "15 درصد تخفیف",  
        category: "رستوران",  
        contact: "021-44144000",  
        featured: ["ویژه", "منتخب"],  
    },  
    {  
        id: 2,  
        title: "فرش بهشتی",  
        image: "/assets/immmg/s6.png",  
        address: "تهران",  
        discount: "5 درصد تخفیف",  
        category: "فرش",  
        contact: "021-44144000",  
        featured: [],  
    },  
    {  
        id: 3,  
        title: "پزشکت",  
        image: "/assets/immmg/s3.png",  
        address: "تهران",  
        discount: "7 درصد تخفیف",  
        category: "بیمارستان و پزشکی",  
        contact: "021-44144000",  
        featured: ["منتخب"],  
    },  
    {  
        id: 4,  
        title: "آجیل دستچی",  
        image: "/assets/immmg/s2.png",  
        address: "البرز",  
        discount: "18 درصد تخفیف",  
        category: "خوراک",  
        contact: "021-44144000",  
        featured: ["ویژه"],  
    },  
    {  
        id: 5,  
        title: "مبلمان نیکرادان",  
        image: "/assets/immmg/s8.png",  
        address: "تهران",  
        discount: "26 درصد تخفیف",  
        category: "لوازم خانگی",  
        contact: "021-44144000",  
        featured: ["ویژه", "منتخب"],  
    },  
    {  
        id: 6,  
        title: "بهراد طب بیدار",  
        image: "/assets/immmg/s5.png",  
        address: "تهران",  
        discount: "15 درصد تخفیف",  
        category: "رستوران",  
        contact: "021-44144000",  
        featured: [],  
    },  
    {  
        id: 7,  
        title: "بیمه دات کام",  
        image: "/assets/immmg/s14.png",  
        address: "تهران",  
        discount: "16 درصد تخفیف",  
        category: "بیمه",  
        contact: "021-44144000",  
        featured: [],  
    },  
    {  
        id: 8,  
        title: "استیل البرز",  
        image: "/assets/immmg/s14.png",  
        address: "تهران",  
        discount: "3 درصد تخفیف",  
        category: "شیرآلات",  
        contact: "021-44144000",  
        featured: ["ویژه"],  
    },  
    {  
        id: 9,  
        title: "سینما تیکت",  
        image: "/assets/immmg/s11.png",  
        address: "البرز",  
        discount: "18 درصد تخفیف",  
        category: "تیاتر و سینما",  
        contact: "021-44144000",  
        featured: ["ویژه", "منتخب"],  
    },  
    {  
        id: 10,  
        title: "چشم پزشکی نور",  
        image: "/assets/immmg/s4.png",  
        address: "تهران",  
        discount: "15 درصد تخفیف",  
        category: "خدمات درمانی",  
        contact: "021-44144000",  
        featured: [],  
    },  
    {  
        id: 11,  
        title: "بلانتون",  
        image: "/assets/immmg/s7.png",  
        address: "تبریز",  
        discount: "8 درصد تخفیف",  
        category: "لوازم خانگی",  
        contact: "021-44144000",  
        featured: ["ویژه", "منتخب"],  
    },  
    {  
        id: 12,  
        title: "الانزا",  
        image: "/assets/immmg/s13.png",  
        address: "تهران",  
        discount: "11 درصد تخفیف",  
        category: "آرایشی و بهداشتی",  
        contact: "021-44144000",  
        featured: [],  
    }, 
];  

export {swiperData}